contexts:
  plgrid_cpu:
    account: rl2algosgpus
    backend_type: slurm
    cmd_type: srun
    context_name: plgrid_cpu
    modules_to_load:
    - plgrid/tools/python/3.6.5
    - plgrid/tools/ffmpeg/3.0
    neptune: true
    partition: plgrid
    resources:
      cpu: 2
      mem: 5G
    slurm_url: <username>@pro.cyfronet.pl
    storage_dir: /net/archive/groups/plggrl_algo/scratch
    user_id: <initials>
    venv: /net/people/plgkcz/tutorial/venv
current_context: t2t_plgrid_cpu
